version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo:/data
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=diego
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=chat-app
    networks:
      - spring-mongo-net

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: diego
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_BASICAUTH_USERNAME: diego
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://diego:123456@mongo:27017/
    depends_on:
      - mongo
    networks:
      - spring-mongo-net

volumes:
  mongo: {}

networks:
  spring-mongo-net:
    driver: bridge