spring:
  data:
    mongodb:
      username: diego
      password: 123456
      host: localhost
      port: 27017
      database: chat-app
      authentication-database: admin

server:
  port: 8088