spring:
  data:
    mongodb:
      # username: diego
      # password: 123456
      # host: localhost
      # port: 27017
      # database: chat-app
      # authentication-database: admin
      uri: mongodb://diego:123456@localhost/chat-app?authSource=admin


#https://www.zup.com.br/blog/spring-actuator
# expor todos
# management:
#   endpoints:
#     web:
#       exposure:
#         include: '*'


# expor os necessário
#management.endpoints.web.base-path
management:
  server:
    port: 8008
  endpoints:
    web:
      base-path: '/portal-admin'
      exposure:
        include: 'health, info, mappings'

server:
  port: 8088